// =============================================================================
// tb_top.sv — Simulation top-level for DECO 16-bit (dec0) Arcade
//
// Combines deco16_arcade + fx68k CPU so the Verilator testbench gets a real
// MC68000 CPU executing Heavy Barrel / Bad Dudes / Robocop ROMs.
//
// deco16_arcade takes the CPU bus as inputs (fx68k is external, here).
// cpu_dout is an OUTPUT from deco16_arcade — the read data mux — fed into
// fx68k.iEdb. cpu_din (fx68k.oEdb) is an INPUT to deco16_arcade.
//
// deco16_arcade generates cpu_dtack_n internally.
// deco16_arcade takes video timing (hpos/vpos/hblank/vblank) as inputs.
// These are generated from software counters in tb_system.cpp and passed here.
//
// Sound CPU (M6502) and audio chips are stubbed — sound ROM not needed
// for CPU bring-up testing.
//
// Clock enables:
//   enPhi1/enPhi2: driven from C++ testbench (GUARDRAILS Rule 13)
//
// MAME reference: src/mame/dataeast/dec0.cpp
// =============================================================================
`default_nettype none

/* verilator lint_off SYNCASYNCNET */
module tb_top (
    // ── Clocks / Reset ──────────────────────────────────────────────────────────
    input  logic        clk_sys,
    input  logic        clk_pix,
    input  logic        reset_n,        // active-low (from testbench)

    // ── Program ROM SDRAM (toggle req/ack protocol) ───────────────────────────
    output logic [26:0] prog_rom_addr,
    input  logic [15:0] prog_rom_data,
    output logic        prog_rom_req,
    input  logic        prog_rom_ack,

    // ── Video Outputs ────────────────────────────────────────────────────────────
    output logic  [7:0] rgb_r,
    output logic  [7:0] rgb_g,
    output logic  [7:0] rgb_b,
    output logic        hsync_n,
    output logic        vsync_n,
    output logic        hblank,
    output logic        vblank,

    // ── Video timing inputs (generated by tb_system.cpp software counters) ────
    input  logic        hblank_n_in,
    input  logic        vblank_n_in,
    input  logic  [8:0] hpos,
    input  logic  [8:0] vpos,
    input  logic        hsync_n_in,
    input  logic        vsync_n_in,

    // ── Player Inputs ────────────────────────────────────────────────────────────
    input  logic  [7:0] joystick_p1,
    input  logic  [7:0] joystick_p2,
    input  logic  [1:0] coin,
    input  logic        service,
    input  logic  [7:0] dipsw1,
    input  logic  [7:0] dipsw2,

    // ── Debug: CPU bus ──────────────────────────────────────────────────────────
    output logic [23:1] dbg_cpu_addr,
    output logic        dbg_cpu_as_n,
    output logic        dbg_cpu_rw,
    output logic [15:0] dbg_cpu_dout,   // write data (CPU→system)
    output logic        dbg_cpu_dtack_n,
    output logic        dbg_cpu_halted_n,

    // ── Clock enables: driven from C++ testbench ─────────────────────────────────
    input  logic        enPhi1,
    input  logic        enPhi2
);

// =============================================================================
// Internal wires
// =============================================================================
// deco16_arcade uses active-low reset_n (passed through from tb_top port)

// CPU bus wires (fx68k drives these → deco16_arcade receives them)
logic [23:1] cpu_addr;
logic [15:0] cpu_dout_w;  // read data: deco16_arcade → fx68k (iEdb)
logic [15:0] cpu_din_w;   // write data: fx68k → deco16_arcade (oEdb)
logic        cpu_rw;
logic        cpu_uds_n;
logic        cpu_lds_n;
logic        cpu_as_n;
logic        cpu_dtack_n;
logic [2:0]  cpu_ipl_n;
logic [2:0]  cpu_fc;

// IACK detection (COMMUNITY_PATTERNS.md Section 1.2)
logic inta_n;
assign inta_n = ~&{cpu_fc[2], cpu_fc[1], cpu_fc[0], ~cpu_as_n};

logic cpu_halted_n_raw;

// =============================================================================
// fx68k — MC68000 CPU
// COMMUNITY_PATTERNS.md Section 1.8 complete port map
// enPhi1/enPhi2 driven from C++ BEFORE eval() (GUARDRAILS Rule 13)
// =============================================================================
fx68k u_cpu (
    .clk        (clk_sys),
    .HALTn      (1'b1),
    .extReset   (~reset_n),  // fx68k takes active-high reset
    .pwrUp      (~reset_n),
    .enPhi1     (enPhi1),
    .enPhi2     (enPhi2),

    .eRWn       (cpu_rw),
    .ASn        (cpu_as_n),
    .LDSn       (cpu_lds_n),
    .UDSn       (cpu_uds_n),
    .E          (),
    .VMAn       (),

    .FC0        (cpu_fc[0]),
    .FC1        (cpu_fc[1]),
    .FC2        (cpu_fc[2]),

    .BGn        (),
    .oRESETn    (),
    .oHALTEDn   (cpu_halted_n_raw),

    .DTACKn     (cpu_dtack_n),
    .VPAn       (inta_n),      // autovector on IACK — NEVER 1'b1
    .BERRn      (1'b1),
    .BRn        (1'b1),
    .BGACKn     (1'b1),

    .IPL0n      (cpu_ipl_n[0]),
    .IPL1n      (cpu_ipl_n[1]),
    .IPL2n      (cpu_ipl_n[2]),

    .iEdb       (cpu_dout_w),  // read data from deco16_arcade
    .oEdb       (cpu_din_w),   // write data to deco16_arcade
    .eab        (cpu_addr)
);

assign dbg_cpu_halted_n = cpu_halted_n_raw;

// =============================================================================
// deco16_arcade — full system (BAC06 tiles, MXC06 sprites, 68K main CPU)
// M6502 sound CPU, YM2203, YM3812, OKI M6295 are stubbed
// =============================================================================
deco16_arcade u_deco (
    .clk_sys        (clk_sys),
    .clk_pix        (clk_pix),
    .reset_n        (reset_n),

    // CPU bus
    .cpu_addr       (cpu_addr),
    .cpu_din        (cpu_din_w),    // INPUT: fx68k.oEdb → deco16_arcade
    .cpu_dout       (cpu_dout_w),   // OUTPUT: deco16_arcade → fx68k.iEdb
    .cpu_lds_n      (cpu_lds_n),
    .cpu_uds_n      (cpu_uds_n),
    .cpu_rw         (cpu_rw),
    .cpu_as_n       (cpu_as_n),
    .cpu_fc         (cpu_fc),
    .cpu_dtack_n    (cpu_dtack_n),  // OUTPUT: deco16_arcade generates dtack
    .cpu_ipl_n      (cpu_ipl_n),

    // Program ROM (toggle req/ack)
    .prog_rom_addr  (prog_rom_addr),
    .prog_rom_data  (prog_rom_data),
    .prog_rom_req   (prog_rom_req),
    .prog_rom_ack   (prog_rom_ack),

    // Video outputs
    .rgb_r          (rgb_r),
    .rgb_g          (rgb_g),
    .rgb_b          (rgb_b),
    .hsync_n        (hsync_n),
    .vsync_n        (vsync_n),
    .hblank         (hblank),
    .vblank         (vblank),

    // Video timing inputs
    .hblank_n_in    (hblank_n_in),
    .vblank_n_in    (vblank_n_in),
    .hpos           (hpos),
    .vpos           (vpos),
    .hsync_n_in     (hsync_n_in),
    .vsync_n_in     (vsync_n_in),

    // Player inputs
    .joystick_p1    (joystick_p1),
    .joystick_p2    (joystick_p2),
    .coin           (coin),
    .service        (service),
    .dipsw1         (dipsw1),
    .dipsw2         (dipsw2),

    // Audio outputs — ignored
    .snd_left       (),
    .snd_right      (),

    // Sound ROM SDRAM — stubbed
    .snd_rom_addr   (),
    .snd_rom_req    (),
    .snd_rom_data   (8'h00),
    .snd_rom_ack    (1'b0)
);

// Debug outputs
assign dbg_cpu_addr    = cpu_addr;
assign dbg_cpu_as_n    = cpu_as_n;
assign dbg_cpu_rw      = cpu_rw;
assign dbg_cpu_dout    = cpu_din_w;
assign dbg_cpu_dtack_n = cpu_dtack_n;

endmodule
