// =============================================================================
// tb_system.cpp — Raizing Arcade (Battle Garegga) Verilator testbench
//
// Wraps tb_top.sv which instantiates raizing_arcade.sv (full bus logic).
// Drives:
//   - Clock (96 MHz system)
//   - Reset (active-low, released after ROM load)
//   - ROM preload via ioctl (prog_rom + snd_rom)
//   - RAM dump output: per-frame work_ram + palette_ram for MAME comparison
//
// Environment variables:
//   N_FRAMES   — number of frames to simulate (default 200)
//   DUMP_VCD   — set to "1" to enable VCD trace (slow)
//   RAM_DUMP   — path for per-frame RAM dump binary
//                Format: [4B LE frame#][64KB work RAM][4KB palette][8KB txt vram][4KB txt sel][512B txt scr]
//                Same as bgaregg_frames.bin generated by mame_ram_dump.lua
//   ROM_PROG   — path to 68K program ROM binary (default: bgaregga_prog.bin)
//   ROM_SND    — path to Z80 audio ROM binary (default: bgaregga_snd.bin)
//
// Output:
//   frame_NNNN.ppm — one PPM file per vblank frame (320×240)
//   Comparison stats printed to stderr when RAM_DUMP + golden provided
//
// Video timing (Battle Garegga / GP9001 standard):
//   320×240 active, Total: 416×264
//   At 96 MHz system clock, pixel clock = 96/12 = 8 MHz
//   → frame duration = 416 × 264 × 12 = 1,318,272 system cycles
// =============================================================================

#include "Vtb_top.h"
#include "Vtb_top___024root.h"
#include "verilated.h"
#include "verilated_vcd_c.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cstdint>
#include <string>
#include <vector>
#include <cinttypes>

// ── Video timing constants (GP9001 standard 320×240) ─────────────────────────
static constexpr int VID_H_ACTIVE  = 320;
static constexpr int VID_V_ACTIVE  = 240;
static constexpr int VID_H_TOTAL   = 416;
static constexpr int VID_V_TOTAL   = 264;
static constexpr int PIX_DIV       = 12;   // 96 MHz / 12 = 8 MHz pixel clock

// Frame duration in system clock half-cycles
static constexpr uint64_t FRAME_HALF_CYCLES =
    (uint64_t)VID_H_TOTAL * VID_V_TOTAL * PIX_DIV * 2;

// =============================================================================
// Frame buffer (320×240)
// =============================================================================
struct FrameBuffer {
    static constexpr int W = VID_H_ACTIVE;
    static constexpr int H = VID_V_ACTIVE;
    std::vector<uint32_t> pixels;
    int x = 0, y = 0;

    FrameBuffer() : pixels(W * H, 0) {}

    void capture(int hpos, int vpos, uint8_t r, uint8_t g, uint8_t b) {
        if (hpos >= 0 && hpos < W && vpos >= 0 && vpos < H)
            pixels[vpos * W + hpos] = ((uint32_t)r << 16) | ((uint32_t)g << 8) | b;
    }

    bool write_ppm(const char* path) const {
        FILE* f = fopen(path, "wb");
        if (!f) { fprintf(stderr, "Cannot write %s\n", path); return false; }
        fprintf(f, "P6\n%d %d\n255\n", W, H);
        for (int y = 0; y < H; y++) {
            for (int x = 0; x < W; x++) {
                uint32_t p = pixels[y * W + x];
                uint8_t rgb[3] = { (uint8_t)(p >> 16), (uint8_t)(p >> 8), (uint8_t)p };
                fwrite(rgb, 1, 3, f);
            }
        }
        fclose(f);
        return true;
    }

    int count_nonblack() const {
        int cnt = 0;
        for (auto p : pixels) if (p) ++cnt;
        return cnt;
    }

    void clear() {
        std::fill(pixels.begin(), pixels.end(), 0u);
        x = 0; y = 0;
    }
};

// =============================================================================
// ROM loading helpers
// =============================================================================

// Load a binary file into a vector.
static std::vector<uint8_t> load_rom(const char* path) {
    FILE* f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "WARNING: cannot open ROM: %s\n", path);
        return {};
    }
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    std::vector<uint8_t> data(sz);
    fread(data.data(), 1, sz, f);
    fclose(f);
    fprintf(stderr, "Loaded ROM: %s (%ld bytes)\n", path, sz);
    return data;
}

// Stream a ROM into raizing_arcade via ioctl.
// raizing_arcade expects 16-bit ioctl_dout, byte-paired from 8-bit ROM data.
// Address is byte address; ROM is loaded word by word (2 bytes per ioctl_wr).
static uint64_t stream_rom_ioctl(Vtb_top* top, const std::vector<uint8_t>& rom,
                                  uint8_t index, uint64_t start_iter) {
    if (rom.empty()) return start_iter;

    uint64_t iter = start_iter;
    size_t nbytes = rom.size();

    for (size_t addr = 0; addr < nbytes; addr += 2) {
        uint8_t lo = rom[addr];
        uint8_t hi = (addr + 1 < nbytes) ? rom[addr + 1] : 0;
        uint16_t word = ((uint16_t)hi << 8) | lo;

        // Hold ioctl_wr high for one rising edge
        top->clk = 1;
        top->ioctl_wr    = 1;
        top->ioctl_addr  = (uint32_t)addr;
        top->ioctl_index = index;
        top->ioctl_dout  = word;
        top->eval();
        iter++;

        top->clk = 0;
        top->eval();
        iter++;
    }

    // Deassert ioctl_wr
    top->clk = 1;
    top->ioctl_wr = 0;
    top->ioctl_addr = 0;
    top->eval();
    iter++;

    top->clk = 0;
    top->eval();
    iter++;

    return iter;
}

// =============================================================================
// RAM dump helpers
// =============================================================================

// Write a 16-bit word as two bytes in 68000 big-endian order.
static inline void write_word_be(FILE* f, uint16_t w) {
    uint8_t b[2] = { (uint8_t)(w >> 8), (uint8_t)(w & 0xFF) };
    fwrite(b, 1, 2, f);
}

// Write N zero bytes.
static inline void write_zeros(FILE* f, size_t n) {
    static const uint8_t zero_buf[4096] = {};
    while (n >= sizeof(zero_buf)) {
        fwrite(zero_buf, 1, sizeof(zero_buf), f);
        n -= sizeof(zero_buf);
    }
    if (n > 0) fwrite(zero_buf, 1, n, f);
}

// Dump one frame of RAM state.
// Format matches mame_ram_dump.lua output:
//   [4B LE frame#] [64KB work RAM] [4KB palette] [8KB text VRAM stub] [4KB text sel stub] [512B text scr stub]
static void dump_frame_ram(FILE* f, uint32_t frame_num, Vtb_top* top) {
    // 4-byte LE frame number
    uint8_t hdr[4] = {
        (uint8_t)(frame_num & 0xFF),
        (uint8_t)((frame_num >> 8) & 0xFF),
        (uint8_t)((frame_num >> 16) & 0xFF),
        (uint8_t)((frame_num >> 24) & 0xFF)
    };
    fwrite(hdr, 1, 4, f);

    // Work RAM: 32768 words × 2 bytes = 64KB
    // Access: top->rootp->tb_top__DOT__u_raizing__DOT__work_ram[i]
    auto& wram = top->rootp->tb_top__DOT__u_raizing__DOT__work_ram;
    for (int i = 0; i < 32768; i++) {
        write_word_be(f, (uint16_t)wram[i]);
    }

    // Palette RAM: 2048 words × 2 bytes = 4KB
    // Access: top->rootp->tb_top__DOT__u_raizing__DOT__palette_ram[i]
    auto& pram = top->rootp->tb_top__DOT__u_raizing__DOT__palette_ram;
    for (int i = 0; i < 2048; i++) {
        write_word_be(f, (uint16_t)pram[i]);
    }

    // Text VRAM: 8KB stub (zeros — not implemented in RTL)
    write_zeros(f, 8192);

    // Text line select: 4KB stub (zeros)
    write_zeros(f, 4096);

    // Text line scroll: 512B stub (zeros)
    write_zeros(f, 512);
}

// =============================================================================
// Golden file comparison
// =============================================================================
struct CompareStats {
    int frames_compared = 0;
    int frames_exact    = 0;
    int total_bytes_compared = 0;
    int total_bytes_matched  = 0;
    long wram_region_bytes   = 65536;  // only compare work RAM (most meaningful)
    int wram_exact_frames    = 0;
    int wram_bytes_matched   = 0;

    void print() const {
        fprintf(stderr, "\n=== RAM Comparison vs Golden ===\n");
        fprintf(stderr, "Frames compared:      %d\n", frames_compared);
        fprintf(stderr, "Work RAM exact:       %d / %d (%.1f%%)\n",
                wram_exact_frames, frames_compared,
                frames_compared > 0 ? 100.0 * wram_exact_frames / frames_compared : 0.0);
        fprintf(stderr, "Work RAM byte match:  %d / %lld (%.1f%%)\n",
                wram_bytes_matched,
                (long long)frames_compared * wram_region_bytes,
                frames_compared > 0 ?
                    100.0 * wram_bytes_matched / ((long long)frames_compared * wram_region_bytes) : 0.0);
        fprintf(stderr, "Total bytes matched:  %d / %d (%.1f%%)\n",
                total_bytes_matched, total_bytes_compared,
                total_bytes_compared > 0 ?
                    100.0 * total_bytes_matched / total_bytes_compared : 0.0);
    }
};

// =============================================================================
// main
// =============================================================================
int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    Verilated::fatalOnError(false);

    // ── Configuration from environment ──────────────────────────────────────
    const char* env_frames   = getenv("N_FRAMES");
    const char* env_vcd      = getenv("DUMP_VCD");
    const char* env_ram_dump = getenv("RAM_DUMP");
    const char* env_rom_prog = getenv("ROM_PROG");
    const char* env_rom_snd  = getenv("ROM_SND");
    const char* env_golden   = getenv("GOLDEN");

    int n_frames = env_frames ? atoi(env_frames) : 200;
    if (n_frames < 1) n_frames = 1;

    const char* rom_prog_path = env_rom_prog ? env_rom_prog : "bgaregga_prog.bin";
    const char* rom_snd_path  = env_rom_snd  ? env_rom_snd  : "bgaregga_snd.bin";

    fprintf(stderr, "=================================================\n");
    fprintf(stderr, "Raizing Arcade (Battle Garegga) simulation\n");
    fprintf(stderr, "Frames requested: %d\n", n_frames);
    fprintf(stderr, "System clock: 96 MHz\n");
    fprintf(stderr, "ROM prog: %s\n", rom_prog_path);
    fprintf(stderr, "ROM snd:  %s\n", rom_snd_path);
    if (env_ram_dump) fprintf(stderr, "RAM dump: %s\n", env_ram_dump);
    if (env_golden)   fprintf(stderr, "Golden:   %s\n", env_golden);
    fprintf(stderr, "=================================================\n");

    // ── Load ROMs ────────────────────────────────────────────────────────────
    auto prog_rom = load_rom(rom_prog_path);
    auto snd_rom  = load_rom(rom_snd_path);

    // ── Instantiate DUT ──────────────────────────────────────────────────────
    Vtb_top* top = new Vtb_top();

    // ── Optional VCD trace ───────────────────────────────────────────────────
    VerilatedVcdC* vcd = nullptr;
    if (env_vcd && env_vcd[0] == '1') {
        Verilated::traceEverOn(true);
        vcd = new VerilatedVcdC();
        top->trace(vcd, 99);
        vcd->open("sim_raizing.vcd");
        fprintf(stderr, "VCD trace enabled: sim_raizing.vcd\n");
    }

    // ── Optional RAM dump file ─────────────────────────────────────────────
    FILE* ram_dump_f = nullptr;
    if (env_ram_dump) {
        ram_dump_f = fopen(env_ram_dump, "wb");
        if (!ram_dump_f) {
            fprintf(stderr, "ERROR: cannot open RAM_DUMP file: %s\n", env_ram_dump);
        } else {
            fprintf(stderr, "RAM dump: %s  (format: 4B frame# + 82432B RAM regions)\n", env_ram_dump);
        }
    }

    // ── Optional golden file for comparison ──────────────────────────────────
    FILE* golden_f = nullptr;
    if (env_golden) {
        golden_f = fopen(env_golden, "rb");
        if (!golden_f) {
            fprintf(stderr, "WARNING: cannot open golden file: %s\n", env_golden);
        } else {
            fprintf(stderr, "Golden comparison enabled\n");
        }
    }

    // ── Initial port state ───────────────────────────────────────────────────
    top->clk       = 0;
    top->rst_n     = 0;   // hold in reset during ROM load
    top->ioctl_wr  = 0;
    top->ioctl_addr  = 0;
    top->ioctl_dout  = 0;
    top->ioctl_index = 0;
    top->sdram_dq_in = 0xFFFF;
    top->joystick_0  = 0x3FF;
    top->joystick_1  = 0x3FF;
    top->dipsw_a     = 0xFF;
    top->dipsw_b     = 0xFF;
    top->eval();

    // ── ROM preload phase (reset held) ───────────────────────────────────────
    uint64_t iter = 0;

    // Hold reset for a few cycles before loading
    for (int i = 0; i < 20; i++) {
        top->clk = top->clk ^ 1;
        top->eval();
        iter++;
    }

    // Load prog ROM (ioctl_index = 0)
    if (!prog_rom.empty()) {
        fprintf(stderr, "Loading prog ROM (%zu bytes)...\n", prog_rom.size());
        iter = stream_rom_ioctl(top, prog_rom, 0, iter);
        fprintf(stderr, "Prog ROM loaded.\n");
    }

    // Load sound ROM (ioctl_index = 2)
    if (!snd_rom.empty()) {
        fprintf(stderr, "Loading sound ROM (%zu bytes)...\n", snd_rom.size());
        iter = stream_rom_ioctl(top, snd_rom, 2, iter);
        fprintf(stderr, "Sound ROM loaded.\n");
    }

    // ── Release reset ────────────────────────────────────────────────────────
    fprintf(stderr, "Releasing reset at iter %" PRIu64 "...\n", iter);
    top->rst_n = 1;

    // ── Simulation state ─────────────────────────────────────────────────────
    int  frame_num       = 0;
    bool done            = false;
    bool prev_vblank     = false;
    bool in_active_area  = false;

    // Pixel counter for frame capture (tied to actual ce_pixel + hblank/vblank signals)
    int  hpix = 0, vpix = 0;
    bool prev_ce_pix = false;

    // Maximum iterations after reset: generous budget
    uint64_t max_iter = iter + (uint64_t)n_frames * FRAME_HALF_CYCLES * 2;

    CompareStats stats;

    FrameBuffer fb;

    fprintf(stderr, "Starting main eval loop (target %d frames)...\n", n_frames);
    uint64_t vcd_ts = 0;

    // Golden frame buffer for comparison
    static uint8_t golden_frame_buf[82436];

    for (; !done && iter < max_iter; iter++) {
        top->clk = top->clk ^ 1;

        if (top->clk == 1) {
            // Sample outputs on rising edge (after eval)
        }

        top->eval();

        if (vcd) {
            vcd->dump(vcd_ts++);
        }

        if (top->clk == 1 && top->rst_n) {
            // ── Pixel capture ─────────────────────────────────────────────────
            // Use ce_pixel + hblank + vblank to capture pixels
            if (top->ce_pixel && !prev_ce_pix) {
                // Rising edge of ce_pixel
            }
            prev_ce_pix = top->ce_pixel;

            // Simple: capture every rising clock when in active area
            if (top->ce_pixel && !top->hblank && !top->vblank) {
                fb.capture(hpix, vpix, top->rgb_r, top->rgb_g, top->rgb_b);
                hpix++;
                if (hpix >= VID_H_ACTIVE) hpix = 0;
            }

            // Track vpos using hblank and vblank
            if (top->ce_pixel) {
                if (top->hblank && hpix != 0) hpix = 0;  // end of active line
                if (top->vblank && vpix != 0 && !prev_vblank) vpix = 0;  // end of frame
                if (!top->hblank && !top->vblank && hpix == 0 && !top->vblank) {
                    // wrapped to next line
                }
            }

            // ── Vblank rising edge = frame boundary ───────────────────────────
            if (top->vblank && !prev_vblank) {
                // End of active display area — process frame
                char fname[64];
                snprintf(fname, sizeof(fname), "frame_%04d.ppm", frame_num);
                fb.write_ppm(fname);

                int nb = fb.count_nonblack();
                fprintf(stderr, "  Frame %4d: %d non-black pixels\n", frame_num, nb);

                // ── RAM dump ──────────────────────────────────────────────────
                if (ram_dump_f) {
                    dump_frame_ram(ram_dump_f, (uint32_t)frame_num, top);
                    if ((frame_num % 10) == 0) fflush(ram_dump_f);
                }

                // ── Golden comparison (inline) ────────────────────────────────
                if (golden_f) {
                    size_t bytes_read = fread(golden_frame_buf, 1, 82436, golden_f);
                    if (bytes_read == 82436) {
                        // Parse golden frame number
                        uint32_t golden_frame =
                            (uint32_t)golden_frame_buf[0] |
                            ((uint32_t)golden_frame_buf[1] << 8) |
                            ((uint32_t)golden_frame_buf[2] << 16) |
                            ((uint32_t)golden_frame_buf[3] << 24);

                        // Compare work RAM (bytes 4 .. 65539)
                        auto& wram = top->rootp->tb_top__DOT__u_raizing__DOT__work_ram;
                        int wram_match = 0;
                        int wram_total = 65536;
                        const uint8_t* gold_wram = golden_frame_buf + 4;

                        for (int i = 0; i < 32768; i++) {
                            uint16_t rtl_word = (uint16_t)wram[i];
                            uint8_t rtl_hi = (uint8_t)(rtl_word >> 8);
                            uint8_t rtl_lo = (uint8_t)(rtl_word & 0xFF);
                            if (rtl_hi == gold_wram[i * 2])     wram_match++;
                            if (rtl_lo == gold_wram[i * 2 + 1]) wram_match++;
                        }

                        bool wram_exact = (wram_match == wram_total);
                        stats.wram_bytes_matched += wram_match;
                        if (wram_exact) stats.wram_exact_frames++;

                        // Total comparison across all regions
                        // Build sim frame bytes to compare against golden
                        // (simplified — just work RAM for now)
                        stats.total_bytes_compared += wram_total;
                        stats.total_bytes_matched  += wram_match;

                        stats.frames_compared++;
                        if (wram_exact) stats.frames_exact++;

                        if (frame_num < 5 || frame_num % 50 == 0) {
                            fprintf(stderr, "    [compare] frame %d (gold=%u) wram %d/%d (%.1f%%)\n",
                                    frame_num, golden_frame,
                                    wram_match, wram_total,
                                    100.0 * wram_match / wram_total);
                        }
                    }
                }

                // Reset pixel counters for next frame
                fb.clear();
                hpix = 0;
                vpix = 0;
                frame_num++;

                if (frame_num >= n_frames) {
                    done = true;
                }
            }

            // Track vblank/pixel position
            prev_vblank = top->vblank;

            // Advance vpix on each hblank rising edge
            if (top->ce_pixel && top->hblank && hpix == 0) {
                // Just entered hblank — increment line
                if (!top->vblank) vpix++;
            }
        }
    }

    // ── Finalize ─────────────────────────────────────────────────────────────
    top->eval();

    if (vcd) { vcd->close(); delete vcd; }
    if (ram_dump_f) { fclose(ram_dump_f); }
    if (golden_f) { fclose(golden_f); }

    fprintf(stderr, "\n=================================================\n");
    fprintf(stderr, "Raizing sim COMPLETE\n");
    fprintf(stderr, "  Frames completed: %d / %d\n", frame_num, n_frames);
    fprintf(stderr, "  Total half-cycles: %" PRIu64 "\n", iter);
    fprintf(stderr, "=================================================\n");

    if (stats.frames_compared > 0) {
        stats.print();
    }

    delete top;
    return 0;
}
